name: Test Dev

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    linting_and_tests:
        runs-on: ubuntu-latest
        environment:
            dev
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install pnpm
          uses: pnpm/action-setup@v4
          with:
            version: 8.15.9

        - name: Install Dependencies
          run: pnpm install

        - name: Check linting Errors
          run: pnpm lint